# makefile for all the exercises in this folder

CC=g++
CC1=clang
CFLAGS= -Wall -g

# exercise 3
exercise3: exercise3.cpp Student_info_1.cpp median.cpp
	$(CC) $^ $(CFLAGS) -o $@

# exercise 4
exercise4: exercise4.cpp Student_info_1.cpp median.cpp
	$(CC) $^ $(CFLAGS) -o $@

# exercise 5
exercise5: exercise5.cpp Student_info_2.cpp median.cpp
	$(CC) $^ $(CFLAGS) -o $@

# exercise 6
exercise6: exercise6.cpp Student_info_1.cpp median.cpp
	$(CC) $^ $(CFLAGS) -o $@

	
